# Generated by Django 4.0.2 on 2022-03-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
